name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: '/searchbar'

      - name: Create .nojekyll file
        run: touch out/.nojekyll

      - name: Verify Deployment Directory
        run: |
          if [ -d "out" ] && [ "$(ls -A out)" ]; then
            echo "Output directory exists and is not empty"
            echo "Contents of out directory:"
            ls -la out/
            echo "Checking for _next directory:"
            ls -la out/_next/ || echo "_next directory not found"
          else
            echo "Output directory does not exist or is empty"
            exit 1
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4